server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservicios02?serverTimezone=UTC&useSSL=false
    username: root
    password:
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: TRANSACTION-SERVICE

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger.html
