spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservicios02?serverTimezone=UTC&useSSL=false
    username: root
    password:
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8081