server:
  port: 8888
spring:
  application:
    name: CONFIG-SERVER
  security:
    user:
      name: admin
      password: admin
  cloud:
    config:
      server:
        git:
          uri: D:\\workspace\\config-server-repo
          clone-on-start: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
